### ISSUE TITLE
Download config problem from Asia

### ISSUE THREAD

**Issue by ryhnhao** [Syzygianinfern0/NuPlan-Download-CLI#4]
Hi!
Well done! It's a very great and useful tool!
But I still have some issues about its generalization around the world :)

It can be seen that we can choose US or Asia to get better download speed from different regions.
![微信截图_20240411150328](https://github.com/Syzygianinfern0/NuPlan-Download-CLI/assets/153728596/77d3b9b3-c64e-4ecc-a7f5-aab1c959a2e3)

How can I change the config in [download_nuplan.py](https://github.com/Syzygianinfern0/NuPlan-Download-CLI/blob/main/download_nuplan.py) to download from Asia. The Amazon region in your default setting is US.

I have tried the following setting, but it doesn't work for me.
![微信截图_20240411150208](https://github.com/Syzygianinfern0/NuPlan-Download-CLI/assets/153728596/707246ac-b0ec-4ee5-be93-b0c3f8c5027a)

BTW, the Amazon region info is [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html), I have tried every Asia Code but failed.

Thanks again and look forward to your reply!

**Comment by Syzygianinfern0** [comment]
Hey! Thanks for your interested in this script. 

From what I see (Chrome Dev Tools > Network Tab), even when we use the different region, the final URL list from which the download would take place is the same. 

```
https://motional-nuplan.s3.amazonaws.com/public/nuplan-v1.1/sensor_blobs/test_set/nuplan-v1.1_test_lidar_0.zip
... <etc>
```

Anyways if you want to use the different region, the only edit that needs to be done is to add `?region=us`or `?region=asia` to the links. 

```diff
links += [BASE_URL + "nuplan-v1.1_test.zip"]
+ links = [each + "?region=asia" for each in links]

download_links = Parallel(n_jobs=12)(delayed(get_download_url)(login_token, link) for link in tqdm(links))
```

But again, it wouldn't make a difference in the zip download links.

**Comment by ryhnhao** [comment]
Same hahaha :)
It's so funny. TYSM anyway!
